### ISSUE TITLE
Invalid identifier type for new references?

### ISSUE THREAD

**Issue by bill-hewitt** [Yelp/terraform-provider-cloudhealth#6]
I'm getting 400 responses when the generated update JSON includes new identifiers being added (e.g., substantial changes to filters or new groups):

curl -v -s -H "Content-Type: application/json" -XPUT "https://chapi.cloudhealthtech.com/v1/perspective_schemas/<perspective_id>?api_key=$CHT_API_KEY" --data-binary @cht_update.json

...returns a 400 with...

{"errors":"Could not verify schema: Constant Reference ID is not a positive integer. ref_id: 910038d7-8a64-96a5-2fe6-d1dbe6475782. Constant Type: Static Group"}

Not sure if this is a result of a change on the API side, but it will make using Terraform to manage Perspectives substantially less useful until fixed.

**Comment by timmow** [comment]
Fixed by https://github.com/Yelp/terraform-provider-cloudhealth/pull/7
